version: "3.9"

networks:
  real:
    driver: bridge

volumes:
  postgres_data_reality:
    driver: local

services:

  postgres:
    container_name: Real-Postgres
    image: postgres:13
    volumes:
      - postgres_data_reality:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8081:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: postgres, real
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - real

  back:
    container_name: Real-Backend
    image: danyilsmirnov/real-backend:1.0
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/real
      SPRING_DATASOURCE_USERNAME: owner_reality_db
      SPRING_DATASOURCE_PASSWORD: owner_reality_db
    ports:
      - "8080:8080"
    networks:
      - real
    depends_on:
      - postgres

  front:
    container_name: Front
    image: danyilsmirnov/reality-front:1.0
    build: .
    ports:
      - "4201:80"
    restart: unless-stopped