version: "2.0"

networks:
  real:
    driver: bridge

volumes:
  postgres_data_reality:
    driver: local

services:

  postgres:
    container_name: PostgresReal
    image: postgres:13
    volumes:
      - postgres_data_reality:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8081:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: postgres, real
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - real

  backend:
    container_name: BackendReal
    image: danyilsmirnov/stell-backend:1.1
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
      SPRING_LIQUIBASE_DROP_FIRST: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/real
      SPRING_DATASOURCE_USERNAME: owner_reality_db
      SPRING_DATASOURCE_PASSWORD: owner_reality_db
    ports:
      - "8080:8080"
    networks:
      - real
    depends_on:
      - postgres

  frontend:
    container_name: FrontReal
    image: danyilsmirnov/stell-front:1.1
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - real
    depends_on:
      - backend